### ISSUE TITLE
createJSON causes segfault

### ISSUE THREAD

**Issue by beamandrew** [cpsievert/LDAvis#15]
I'm using mallet and LDAvis to analyze a corpus of approximately 1 million documents, following this example pretty closely: http://cpsievert.github.io/LDAvis/reviews/reviews.html

After the model is fit, I run checkInputs and it tells me everything looks good. However, once I call createJSON, R crashes with the following information:

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	rsession.exe
  Application Version:	0.98.1028.0
  Application Timestamp:	53ed1f34
  Fault Module Name:	lapack.dll
  Fault Module Version:	3.2.63987.0
  Fault Module Timestamp:	5243035d
  Exception Code:	c0000005
  Exception Offset:	000000000000464c
  OS Version:	6.1.7601.2.1.0.18.10
  Locale ID:	1033
  Additional Information 1:	24cf
  Additional Information 2:	24cfe87c8f9b583e72c7671cd3b0a66d
  Additional Information 3:	557d
  Additional Information 4:	557d717948b0b58e03da185573deb738

For reference, I'm using an HPC virtual desktop running Windows 2008 R2 enterprise with 256GB of RAM.  I was able to save and transfer the object resulting from checkInputs (the "out" object from the example) to another machine (Mac/OSX) and createJSON was successful.

**Comment by cpsievert** [comment]
Closing this since there is no way to know if this is still a problem. Feel free to reopen @beamandrew if haven't resolved the problem.
