### ISSUE TITLE
Phi test and Error message in CreateJSON

### ISSUE THREAD

**Issue by chdoig** [cpsievert/LDAvis#22]
Hi, I was running into this issue when using LDAVis

```
> createJSON(phi=phi_n, theta = theta_n, doc.length = doc.length, vocab=vocab_vector, term.frequency=term_frequency)
Error in createJSON(phi = phi_n, theta = theta_n, doc.length = doc.length,  : 
  Columns of phi don't all sum to 1.
```
But the columns where in fact normalized to sum 1, by running previously:
```
phi_n <- sweep(phi, 2, colSums(phi), FUN="/")
```
So, I checked the source code:
https://github.com/cpsievert/LDAvis/blob/master/R/createJSON.R#L144-L147

And it seems that the phi_test and the output message don't match:

phi_test is testing for phi *rows* summing to 1, and the error message is saying that the phi *columns* should sum to 1.

Thanks for this library, looks great!

**Comment by kshirley** [comment]
Thanks for catching this! In development we flipped back and forth regarding the orientation of phi, hence the mixup in our error message.

As it stands the *rows* of phi need to sum to one, so we fixed the error message to reflect this.

Are you able to get it to work (setting the rows of phi to sum to one)?

-k

**Comment by chdoig** [comment]
Thanks! That worked!

Just tried serVis() and it looks great! :)
