### ISSUE TITLE
Clarification of license

### ISSUE THREAD

**Issue by bmabey** [cpsievert/LDAvis#30]
The `LICENSE` indicates the copyright holder but not the type of license.  Could you please specify what it is and [choose one](http://choosealicense.com/licenses/) if needed? (MIT, Apache, etc..)

I would like port the R portion of LDAvis to python and ideally reuse the JS code so I'm wondering if that is possible under the project's license.

**Comment by bmabey** [comment]
Never mind, I just saw that [it is under MIT](https://github.com/cpsievert/LDAvis/blob/master/DESCRIPTION#L20).

I'll let you know when I've done a python port. :)

**Comment by cpsievert** [comment]
Please do!! :)
