### ISSUE TITLE
Missing "check.inputs" function

### ISSUE THREAD

**Issue by AHMcKenzie** [cpsievert/LDAvis#36]
Hi Carson,
I recently updated R and reinstalled the latest packages, but also discovered that function "check.inputs" is no longer there. I didn't find any reference about this change, is it a design change, or perhaps an omission? Thanks.
Alex

**Comment by cpsievert** [comment]
Ah, yea, sorry, that should've been documented better. We incorporated those checks into `createJSON()` itself, so there is no longer a need for it.
