### ISSUE TITLE
Error: could not find function "check.inputs"

### ISSUE THREAD

**Issue by williamxing** [cpsievert/LDAvis#37]
I am really interested in LDAvis and cool visualizations. I have the basic code running like the " Twenty Newsgroups" data. However, the visualization generated does not have the "cluster" button and "topic distance calculation" button etc like "https://gallery.shinyapps.io/LDAelife/". I want to have all the buttons on the top. 

I am encountering a problem when I tried different code sources: "Error: could not find function "check.inputs"" this codes is from  "https://github.com/cpsievert/cpsievert.github.com/blob/master/elife/elife.R".   

The problem I have is from this line:  "z <- check.inputs(K=max(topic.id), W=max(token.id), phi, token.frequency, vocab, topic.proportion)" and it said "Error: could not find function "check.inputs" ". 

I am new to R and appreciate your feedback on this. 

Thank you.

**Comment by cpsievert** [comment]
If you want the clustering ability, see #26. 

I should document this better, but that elife script is using version 0.1 (we deprecated `check.inputs()` in version 0.2 so that script doesn't work with the newest version).

**Comment by williamxing** [comment]
Thank you so much. It almost works. I checked the #26, and when I used the version0.1, it solved the "check.inputs"  problem. However, when I ran into the final stage for output, I got stuck on another problem and particular line: 
"library(shiny)
with(z, createJSON(phi, term.frequency, vocab, topic.proportion))"

It keeps showing the message "Error in sum(term.frequency) : invalid 'type' (character) of argument". 

Do you have an example code on how to "Note that the inputs to createJSON() are slightly different in this version (from #26 )" use the createJSON() for the 0.1 version. 


Here is the code I used: 

lda_inf <- posterior(lda, dtm)
phi = t(lda_inf$terms)
term.frequency = colSums(as.matrix(dtm))
vocab = names(term.frequency)
topic.proportion = as.vector(colSums(lda_inf$topics)) / nrow(dtm)
ldavis = list(phi = phi,
              term.frequency = term.frequency,
              vocab = vocab,
              topic.proportion = topic.proportion)
library(LDAvis)
with(ldavis, colSums(phi))
all(with(ldavis, rownames(phi) == vocab))
z <- with(ldavis, check.inputs(K = 8, W = 773, 
                               phi, term.frequency, vocab, topic.proportion))
with(ldavis, order(topic.proportion, decreasing = TRUE))
with(z, colnames(phi))
colnames(z$phi) <- seq_len(z$K)
json <- with(z, createJSON(K, phi, term.frequency, vocab,
                           topic.proportion, n.terms=30, dist.measure = "JS"))

library(shiny)
with(z, createJSON(phi, term.frequency, vocab, topic.proportion))

Thanks again.

**Comment by cpsievert** [comment]
We have a number of links to examples on the README.md that use the current version

**Comment by williamxing** [comment]
I mean for the 0.1version, the previous version with the cluster button. I do need the cluster button. Is there a sample? Or some documents on the previous version? 

Thanks a lot. I really appreciate.

**Comment by cpsievert** [comment]
Oh, have you tried `runShiny()` instead of `createJSON()`?

**Comment by williamxing** [comment]
Awesome! ! runShiny() works. Only the circle for each topic is really big and take the whole screen. I guess it might be because my topic number is too small (k = 4)? Or because of the topic proportion. Any suggestion? 

I will try bigger k and let you know the final results :+1:

**Comment by williamxing** [comment]
It works perfect when I enlarge the K. Thanks again for the help. Very cool package :+1:

**Comment by williamxing** [comment]
Hi, I have follow up question on the LDAvis 1.0. All things work out but the size or the area of the topics are not proportional to their prevalence. Basically, all the topics are the same size. Any suggestions? I can print out the topic.proportion, which seems fine on the screen. I used runShiny() to visualize. 

> topic.proportion
 [1] 0.009636156 0.009729711 0.009763731 0.009984861 0.010086921 0.010444131 0.010495161 0.010818350
 [9] 0.011039480 0.011422205 0.011813434 0.011949514 0.012043069 0.012451309 0.012510844 0.012629914
[17] 0.012655429 0.012868054 0.012868054 0.012902074 0.012919084 0.012936093 0.012944598 0.013038153
[25] 0.013310313 0.013488918 0.013616493 0.013676028 0.013888653 0.013897158 0.014058752 0.014203337
[33] 0.014211842 0.014305397 0.014339417 0.014356427 0.014466992 0.014484002 0.014501012 0.014543537
[41] 0.014543537 0.014577557 0.014603072 0.014611577 0.014764667 0.014917757 0.015053837 0.015394036
[49] 0.015462076 0.015691711 0.015751246 0.015938356 0.015938356 0.016023406 0.016261546 0.016448655
[57] 0.016618755 0.016746330 0.016763340 0.016856895 0.016873905 0.017061015 0.017086530 0.017154570
[65] 0.017622344 0.018336764 0.018353774 0.018404804 0.018736498 0.022104475
