### ISSUE TITLE
rccp crash?

### ISSUE THREAD

**Issue by tingleyd** [cpsievert/LDAvis#38]
Hi,
On several PC's I've had the following problem trying to run the demo.

Sys.info()
                     sysname                      release                      version                     nodename                      machine 
                   "Windows"                      "7 x64" "build 7601, Service Pack 1"    

Error in withCallingHandlers(tryCatch(evalg((function (hash=TRUE, parent = parent.frame(),  :
object '.rcpp_warning_recorder' not found

R then aborts.

I'm using R 3.1.2

Any suggestions?

**Comment by cpsievert** [comment]
Try updating Rcpp

http://stackoverflow.com/questions/28966800/error-withcallinghandlers-crashing-r

**Comment by tingleyd** [comment]
thanks Carson, that works.
Do you what is requiring Rcpp as I don't believe LDAvis depends on that
package?
thanks
Dustin

Dustin Tingley
Government Department
Harvard University
http://scholar.harvard.edu/dtingley

**Comment by cpsievert** [comment]
Great, good to hear, thanks for reporting. LDAvis depends on plyr which in turn depends on Rcpp.

**Comment by kshirley** [comment]
Hey Carson, thanks for helping Dustin.

Question for you: I don't see the plyr dependence in our "DESCRIPTION" file. Is the dependence encoded somewhere else?

I, too, find it a bit funny that we're getting tripped up by updates to Rcpp, which we don't use. Is there a way we can avoid this? Or do we just have to be vigilant and test LDAvis every time our dependencies are updated?

**Comment by cpsievert** [comment]
Ah, good point, I forgot that we removed the plyr dependency. 

I'm guessing this has to do either with devtools or RStudio -- ([note how updating Rcpp fixed this problem with shiny, but shiny doesn't rely on Rcpp](http://stackoverflow.com/questions/29241455/shiny-causes-rstudio-to-crash))

That being said, yes, it's always a good idea to test using the most current versions ;)
