### ISSUE TITLE
Can LDAvis support the analysis of texts in Chinese

### ISSUE THREAD

**Issue by nvxiansheng2015** [cpsievert/LDAvis#44]
Can LDAvis support the analysis of texts in Chinese?

**Comment by kshirley** [comment]
I'm not sure about that. Could you point us to an example data set that we could experiment with?

**Comment by niutyut** [comment]
hello，
i  povide an example data set，

1、科学学作为一门新兴学科,如果没有科学而严谨的逻辑体系,是会妨碍它的发展的。建立科学学的逻辑体系的前提是明确科学学的研究对象、范围、方面和内容以及内容之间的逻辑联系。在建立科学学体系时,不能硬套某种僵化的框架,而要围绕科学学研究的对象、本质、关系和规律,进行创造性探讨。
2、本文阐明了生产劳动的内涵及在各种社会历史形态下的变化,科学劳动在特定历史条件下成为生产劳动的根据和途径。科学劳动队伍形成的特点以及社会主义社会中科学劳动的性质和地位等问题。
3、科学发现的过程,类似于采掘过程。它总是沿着不同物质层次(或能量级别)不断推进的,不同时代总有不同的科学成为“当采学科”。当采学科转移的历史条件,乃是当采层次所包含的基本换能效应的发现。在这一条件尚未满足以前,科学史上往往出现大规模的“回采现象”。“当采”与“回采”都是影响科学发展的重要因素,也是预测未来科学发展战略趋势的有效手段。
4、科学研究就是探索未知的新事物或新规律,并从中导致科学发现和技术发明。科学研究是一种艰苦的创造性劳动,对推进社会历史发展起着重要的作用。取得科研成果的劳动之所以非常艰巨,主要原因之一在于实验条件有时是极其恶劣的,它必然危及科学家的身体健康甚至生命。以遭受过剂量辐射损害的诺贝尔物理奖获得者来说,贝克勒尔寿命是56岁,居里夫人是67岁,费米是53岁,劳伦斯是57岁。他们
5、本文探讨了科技发展战略的内容、特点、研究方法以及制定科技发展战略需要建立的组织系统、信息系统、预测系统、指标系统、模型系统等基础性工作。
6、本文以机械部门为例,探讨了有重点地发展新技术、加快传统工业的技术改造、坚持以应用研究为主、鼓励军用向民用转移、奖励成果推广应用、加强科技情报交流、发挥学术组织作用、引进国外先进技术、加强智力开发以及改革科技管理体制等政策问题。

i use topicmodels to deal with this data set .
i hope you can help me to display it with LDAvis.thank you!!

**Comment by cpsievert** [comment]
See https://github.com/cpsievert/LDAvis/issues/50#issuecomment-308465124
