### ISSUE TITLE
Topic numbers from lda is not the same those from LDAvis 

### ISSUE THREAD

**Issue by BeomSooKim** [cpsievert/LDAvis#46]
Hi,

I'm using 'lda' and 'LDAvis' packages for topic modeling 
I got topic numbers from 'lda' packages using 'topics()' function.
but it's not correspond to the topic numbers from 'LDAvis' packages

I guess there are some calculation about marginal distribution but i don't know what it is

can i calculate it? or how can i konw the relationship between two topic numbers?

**Comment by cpsievert** [comment]
Please see #42
