### ISSUE TITLE
LDAvis display chinese problem

### ISSUE THREAD

**Issue by niutyut** [cpsievert/LDAvis#49]
i am chinese user of LDAvis ,when i display chinese language ,i find its messy code,
lda.vis <- topicmodels_json_ldavis(title.abstract.model, myCorp, tfidf_dtm)
##visualize lda model
serVis(lda.vis)

how to do it  with UTF-8 or gbk?
please help me!!thank you

**Comment by cpsievert** [comment]
Duplicate of #44
