### ISSUE TITLE
dist() with jensenShannon returns Nan 

### ISSUE THREAD

**Issue by lmkirvan** [cpsievert/LDAvis#55]
I can't quit figure out why (as the jensen Shannon distance function looks okay) but 

`jensenShannon <- function(x, y) {
  m <- 0.5*(x + y)
  0.5*sum(x*log(x/m)) + 0.5*sum(y*log(y/m))
}

dist.mat <- proxy::dist(x = phi, method = jensenShannon)`

returns Nan using phi.

**Comment by cpsievert** [comment]
duplicate of #56
