### ISSUE TITLE
LDAvis in Jupyter Notebook

### ISSUE THREAD

**Issue by methodds** [cpsievert/LDAvis#57]
Hi,

I'm currently working with the [R-kernel](https://github.com/IRkernel/IRkernel) for Jupyter Notebooks and try to include LDAvis outputs in such notebooks. Unfortunately this does not work in comparison to usual plots which work flawlessly. It only works when the visualisation is opened in a new browser windows.

The python adapation [pyLDAvis](https://github.com/bmabey/pyLDAvis) offers a little helper function with which visualisations can directly be included. Is this also possible for the R version?

Cheers

**Comment by cpsievert** [comment]
You could use `serVis()` to write the HTML/JS/JSON to disk, then embed via an `<iframe>`
