### ISSUE TITLE
color parameter in serVis for more customized visualizations

### ISSUE THREAD

**Issue by MarcinKosinski** [cpsievert/LDAvis#63]
By now red and blue colors are set to be non-changebale in `/inst/htmljs/ldavis.js` https://github.com/cpsievert/LDAvis/blob/master/inst/htmljs/ldavis.js#L32

What would you say about letting user to provide his own colors by additional parameter in serVis?

![ldavis_colours](https://cloud.githubusercontent.com/assets/6773454/17107323/fa5d3cd4-528e-11e6-9e4a-94f0cfb66838.png)

**Comment by MarcinKosinski** [comment]
@cpsievert moreover, do you think this is possible to set coloring to more than 2 groups, e.g. points divided to `n` groups where every group has different `baseline` color (and maybe even different `highlight` color) :) ?

LDAvis is great, and can be extended to be greater : )

**Comment by sixtyfive** [comment]
It'd also be cool to have serVis not complain about an already existing directory on subsequent runs, but only overwrite the data file and not the rest. That way, people could modify the HTML/CSS/JS to their hearts' contents.

**Comment by MarcinKosinski** [comment]
never mind about this feature - one could change colors himself
