### ISSUE TITLE
Lambda slider and term selection broken?

### ISSUE THREAD

**Issue by sixtyfive** [cpsievert/LDAvis#69]
I remember seeing fully working LDAvis pages in the past, especially the movie reviews example. Now, however, both the lambda slider and clicking on terms does not work (ref. e.g. http://cpsievert.github.io/LDAvis/reviews/vis/#topic=3&lambda=0.6&term=). Also the topic selection bar in the upper left corner looks a little messed up. Did something break in LDAvis or is this another component's fault?

Unfortunately, the webdev features of Firefox and Chrome don't show any errors, so I don't know how to debug the problem... :disappointed:

**Comment by cpsievert** [comment]
That link looks ok to me, could you be more specific?
