### ISSUE TITLE
serVis is not handling over the server config parameters 

### ISSUE THREAD

**Issue by kbzsl** [cpsievert/LDAvis#72]
I was trying to set the the host to  0.0.0.0 (to listen to all IP addresses), but this parameter is not passed over to the servr::httd function. 
For example, the
`serVis(d.json, host = "0.0.0.0")`
is not working (the same applies to any server config parameter).

Only the directory parameter is passed to the httd function:
`servr::httd(dir = out.dir)`

**Comment by cpsievert** [comment]
The `...` in `serVis()` are passed to `gistr::gist_create()`, but you could do this:


```r
serVis(json, "myvis", FALSE)
sevr::httd("myvis", host = "0.0.0.0")
```
