### ISSUE TITLE
Plot output opens in RStudio IDE and not browser

### ISSUE THREAD

**Issue by segranp** [cpsievert/LDAvis#76]
Hi

Great package. Thank you for developing. 

I am able to use LDAvis to create Shiny app successfully. However, my output plot opens in RStudio IDE only and not browser. The element created in ui.R opens in browser.

Here is the code - https://github.com/segranp/test 

Look forward to your help.

Thank you

**Comment by cpsievert** [comment]
> my output plot opens in RStudio IDE only and not browser. 

Change your browser defaults and/or click on the "open in web browser" icon
