### ISSUE TITLE
Does the reorder.topics parameter do anything?

### ISSUE THREAD

**Issue by jamesLSI** [cpsievert/LDAvis#79]
Hi,

Does the reorder.topics parameter do anything? I need to try and keep the topicmodels numbering due to the number of different models I'll be producing and how we're using the output but whether '= TRUE' or '= FALSE' the vis is exactly the same.

I've seen issues #42 and #46 on topic numbering along with https://github.com/cpsievert/LDAvis/blob/master/R/createJSON.R but am none the wiser.

Thanks
James

**Comment by dyuval** [comment]
Hi James,

What version of LDAvis are you using? I believe that the reorder.topics parameter is not included in the CRAN version, but is available in the dev version. I had a similar need (of wanting to keep the order of topics) and was able to do it using the dev version.

Hope it is helpful!
Yuval

**Comment by jamesLSI** [comment]
Hi Yuval,

I’m using LDAvis_0.3.2 so the latest CRAN version I reckon. You think installing this version will do the job: devtools::install_github("cpsievert/LDAvis") ?

Thanks
James

James Currer
Mobile: +44 07920 750 675
uk.linkedin.com/in/jamescurrer
